# Generated by Django 3.1.3 on 2020-11-11 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=250)),
                ('body', models.TextField()),
                ('sendTo', models.EmailField(max_length=254)),
                ('sendDate', models.DateTimeField(blank=True, null=True)),
                ('abstract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.abstractsubmission')),
            ],
        ),
    ]
