# Generated by Django 3.1.3 on 2020-11-18 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractsubmission',
            name='consented',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='abstractsubmission',
            name='submitter_institution',
            field=models.CharField(default='c2dh', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='abstractsubmission',
            name='submitter_orcid',
            field=models.CharField(default='0000-0002-0237-2532', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contributor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='orcid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='url',
            field=models.URLField(blank=True, max_length=254, null=True),
        ),
        migrations.DeleteModel(
            name='Email',
        ),
    ]
