# Generated by Django 3.1.3 on 2020-11-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20201118_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractsubmission',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
