# Generated by Django 3.1.3 on 2020-11-27 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_abstractsubmission_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AbstractSubmission',
        ),
        migrations.DeleteModel(
            name='Contributor',
        ),
        migrations.DeleteModel(
            name='Ressource',
        ),
    ]
