# Generated by Django 3.1.3 on 2020-11-18 09:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="id", primary_key=True, serialize=False),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("lastname", models.CharField(max_length=50)),
                ("firstname", models.CharField(max_length=50)),
                ("orcid", models.CharField(blank=True, max_length=50, null=True)),
                ("affiliation", models.CharField(max_length=250)),
            ],
            options={
                "ordering": ["lastname"],
            },
        ),
        migrations.CreateModel(
            name="Dataset",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="id", primary_key=True, serialize=False),
                ),
                ("url", models.URLField(blank=True, max_length=254, null=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Abstract",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="id", primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=250)),
                ("abstract", models.TextField()),
                (
                    "submitted_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("validation_date", models.DateTimeField(blank=True, null=True)),
                ("contact_orcid", models.CharField(max_length=50)),
                ("contact_affiliation", models.CharField(max_length=250)),
                ("contact_email", models.EmailField(max_length=254)),
                ("contact_astname", models.CharField(max_length=50)),
                ("contact_firstname", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("ACCEPTED", "Accepted"),
                            ("DECLINED", "Declined"),
                        ],
                        default="SUBMITTED",
                        max_length=15,
                    ),
                ),
                ("consented", models.BooleanField(default=False)),
                ("authors", models.ManyToManyField(to="jdhapi.Author")),
                ("datasets", models.ManyToManyField(to="jdhapi.Dataset")),
            ],
            options={
                "ordering": ["title"],
            },
        ),
    ]
