# Generated by Django 3.1.3 on 2020-11-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdhapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abstract',
            old_name='contact_astname',
            new_name='contact_lastname',
        ),
        migrations.AlterField(
            model_name='abstract',
            name='authors',
            field=models.ManyToManyField(related_name='authors', to='jdhapi.Author'),
        ),
        migrations.AlterField(
            model_name='abstract',
            name='datasets',
            field=models.ManyToManyField(related_name='datasets', to='jdhapi.Dataset'),
        ),
    ]
