# Generated by Django 3.1.3 on 2020-11-19 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdhapi', '0002_auto_20201118_1732'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abstract',
            options={'ordering': ['submitted_date']},
        ),
    ]
