# Generated by Django 3.1.3 on 2020-11-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdhapi', '0003_auto_20201119_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstract',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='authors', to='jdhapi.Author'),
        ),
        migrations.AlterField(
            model_name='abstract',
            name='datasets',
            field=models.ManyToManyField(blank=True, related_name='datasets', to='jdhapi.Dataset'),
        ),
    ]
