# Generated by Django 3.1.3 on 2020-11-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdhapi', '0004_auto_20201123_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstract',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='abstracts', to='jdhapi.Author'),
        ),
        migrations.AlterField(
            model_name='abstract',
            name='datasets',
            field=models.ManyToManyField(blank=True, related_name='abstracts', to='jdhapi.Dataset'),
        ),
    ]
