# Generated by Django 3.1.3 on 2021-05-12 18:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jdhapi', '0006_auto_20201127_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('publication_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('abstract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='jdhapi.abstract')),
                ('repository_url', models.URLField(blank=True, max_length=254, null=True)),
                ('notebook_url', models.URLField(blank=True, max_length=254, null=True)),
                ('notebook_commit_hash', models.CharField(blank=True, default='', help_text='store the git hash', max_length=22)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('INTERNAL_REVIEW', 'Internal_review'), ('EXTERNAL_REVIEW', 'External_review'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=15)),
                ('repository_type', models.CharField(choices=[('GITHUB', 'Github'), ('GITLAB', 'Gitlab')], default='GITHUB', max_length=15)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jdhapi.issue')),
            ],
        ),
    ]
