# Generated by Django 3.1.3 on 2021-05-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdhapi', '0009_auto_20210517_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, default=dict, help_text='JSON format', verbose_name='data contents')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('keyword', 'keyword'), ('tool', 'tool')], default='keyword', max_length=32)),
            ],
            options={
                'unique_together': {('name', 'category')},
            },
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, to='jdhapi.Tag'),
        ),
    ]
