# Generated by Django 3.1.3 on 2021-05-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdhapi', '0010_auto_20210517_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='authors',
            field=models.ManyToManyField(blank=True, to='jdhapi.Author'),
        ),
    ]
