# Generated by Django 3.1.3 on 2021-05-17 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdhapi', '0011_article_authors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='authors',
        ),
    ]
