# Generated by Django 3.1.3 on 2021-05-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdhapi', '0013_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='authors',
            field=models.ManyToManyField(through='jdhapi.Role', to='jdhapi.Author'),
        ),
    ]
