# Generated by Django 3.1.3 on 2021-05-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdhapi', '0015_auto_20210521_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstract',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('ABANDONED', 'Abandoned')], default='SUBMITTED', max_length=15),
        ),
    ]
