# Generated by Django 3.1.3 on 2021-06-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdhapi', '0016_auto_20210521_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='pid',
            field=models.CharField(default='jdh001', max_length=10, unique=True),
        ),
    ]
