# Generated by Django 3.1.3 on 2021-06-25 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdhapi', '0018_auto_20210611_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='notebook_url',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
