# Generated by Django 3.1.3 on 2021-08-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdhapi', '0020_auto_20210714_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='citation',
            field=models.JSONField(blank=True, default=dict, help_text='JSON format', verbose_name='data contents'),
        ),
        migrations.AddField(
            model_name='article',
            name='fingerprint',
            field=models.JSONField(blank=True, default=dict, help_text='JSON format', verbose_name='data contents'),
        ),
        migrations.AddField(
            model_name='article',
            name='notebook_ipython_url',
            field=models.URLField(blank=True, max_length=254, null=True),
        ),
    ]
