# Generated by Django 3.1.3 on 2021-08-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdhapi', '0021_auto_20210826_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='citation',
            field=models.JSONField(blank=True, default=dict, help_text='JSON format', verbose_name='citation contents'),
        ),
        migrations.AlterField(
            model_name='article',
            name='fingerprint',
            field=models.JSONField(blank=True, default=dict, help_text='JSON format', verbose_name='fingerprint contents'),
        ),
    ]
