# Generated by Django 3.1.3 on 2021-10-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdhapi', '0022_auto_20210826_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='doi',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
