# Generated by Django 3.1.3 on 2022-02-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdhapi', '0024_issue_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='category',
            field=models.CharField(choices=[('keyword', 'keyword'), ('tool', 'requirement'), ('narrative', 'narrative'), ('hermeneutic', 'hermeneutic')], default='keyword', max_length=32),
        ),
    ]
