# Generated by Django 3.1.3 on 2022-03-02 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdhapi', '0025_auto_20220222_1538'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('name', 'category', 'data')},
        ),
    ]
