# Generated by Django 3.1.3 on 2022-07-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdhapi', '0026_article_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='copyright_type',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('CC_BY', 'CC-BY'), ('CC_BY_NC_ND', 'CC-BY-NC-ND')], default='DRAFT', max_length=15),
        ),
    ]
