# Generated by Django 3.1.3 on 2022-07-29 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdhapi', '0027_article_copyright_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='issue',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='volume',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
