# Generated by Django 3.2.14 on 2022-09-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdhapi', '0029_issue_cover_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('TECHNICAL_REVIEW', 'Technical_review'), ('PEER_REVIEW', 'Peer_review'), ('DESIGN_REVIEW', 'Design_review'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=25),
        ),
    ]
