# Generated by Django 3.2.14 on 2022-09-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdhapi', '0031_alter_article_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstract',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('ABANDONED', 'Abandoned'), ('SUSPENDED', 'Suspended')], default='SUBMITTED', max_length=15),
        ),
        migrations.AlterField(
            model_name='article',
            name='doi',
            field=models.CharField(blank=True, help_text='Doi received from ScholarOne -  10.1515/JDH.YYYY.XXXX.RX', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='notebook_ipython_url',
            field=models.URLField(blank=True, help_text='Raw GitHub ipynb URL', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='notebook_path',
            field=models.CharField(blank=True, help_text='Notebook file name with .ipynb', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='notebook_url',
            field=models.CharField(blank=True, help_text="Article's preview URL - All the caracters after the url : https://journalofdigitalhistory.org/en/notebook-viewer/", max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='repository_url',
            field=models.URLField(blank=True, help_text="GitHub's repository URL ", max_length=254, null=True),
        ),
    ]
