# Generated by Django 3.2.14 on 2022-09-23 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdhapi', '0033_auto_20220923_1450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abstract',
            old_name='call_paper',
            new_name='callpaper',
        ),
    ]
