# Generated by Django 3.2.14 on 2022-09-23 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdhapi', '0034_rename_call_paper_abstract_callpaper'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callofpaper',
            options={'ordering': ['title']},
        ),
    ]
