# Generated by Django 3.2.14 on 2022-09-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdhapi', '0035_alter_callofpaper_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='callofpaper',
            name='folder_name',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
