# Generated by Django 3.2.14 on 2022-09-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdhapi', '0036_callofpaper_folder_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstract',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('ABANDONED', 'Abandoned'), ('SUSPENDED', 'Suspended'), ('PUBLISHED', 'Published')], default='SUBMITTED', max_length=15),
        ),
    ]
