# Generated by Django 3.2.14 on 2024-01-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdhapi', '0038_article_dataverse_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='full_url_article_path',
            field=models.CharField(blank=True, help_text='Full URL of the article', max_length=254, null=True),
        ),
    ]
