# Generated by Django 3.2.14 on 2024-02-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdhapi', '0038_article_dataverse_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='is_open_ended',
            field=models.BooleanField(default=True),
        ),
    ]
