# Generated by Django 3.2.14 on 2024-04-25 14:06

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jdhapi', '0039_issue_is_open_ended'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
