# Generated by Django 5.1.6 on 2025-04-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdhapi', '0041_alter_author_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='bluesky_id',
            field=models.CharField(blank=True, max_length=26, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='facebook_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='github_id',
            field=models.CharField(default='default_github_id', max_length=39),
        ),
    ]
