# Generated by Django 5.1.6 on 2025-04-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdhapi', '0042_author_bluesky_id_author_facebook_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstract',
            name='languagePreference',
            field=models.CharField(choices=[('Python', 'Python'), ('R', 'R'), ('Default', 'Default')], default='Default', max_length=10),
        ),
    ]
