# Generated by Django 5.1.6 on 2025-04-16 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdhapi', '0043_abstract_languagepreference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstract',
            name='contact_orcid',
        ),
    ]
