# Generated by Django 5.1.6 on 2025-04-16 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdhapi', '0044_remove_abstract_contact_orcid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abstract',
            old_name='languagePreference',
            new_name='language_preference',
        ),
    ]
