# Generated by Django 5.1.6 on 2025-04-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdhapi', '0045_rename_languagepreference_abstract_language_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='github_id',
            field=models.CharField(blank=True, max_length=39, null=True),
        ),
    ]
