# Generated by Django 5.1.6 on 2025-07-04 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdhapi', '0047_alter_author_bluesky_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstract',
            name='contact_email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
