# Generated by Django 5.1.6 on 2025-07-09 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdhapi', '0048_alter_abstract_contact_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CallOfPaper',
            new_name='CallForPaper',
        ),
    ]
