# Generated by Django 5.1.6 on 2025-08-12 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdhapi', '0049_rename_callofpaper_callforpaper'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstract',
            name='issue',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abstracts', to='jdhapi.article'),
        ),
    ]
