# Generated by Django 5.1.6 on 2025-08-12 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdhapi', '0050_abstract_issue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstract',
            name='issue',
        ),
    ]
