# Generated by Django 5.1.6 on 2026-02-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdhapi', '0051_remove_abstract_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='ojs_submission_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
