# Generated by Django 5.1.6 on 2026-03-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdhapi', '0052_article_ojs_submission_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='linkedin_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('TECHNICAL_REVIEW', 'Technical review'), ('PEER_REVIEW', 'Peer review'), ('DESIGN_REVIEW', 'Design review'), ('COPY_EDITING', 'Copy editing'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=25),
        ),
    ]
