# Generated by Django 5.1.6 on 2026-04-23 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdhapi', '0053_author_linkedin_id_alter_article_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('FACEBOOK', 'Facebook'), ('BLUESKY', 'Bluesky')], max_length=20)),
                ('url', models.URLField(blank=True, max_length=254, null=True)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('published_time', models.DateTimeField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='jdhapi.article')),
            ],
        ),
    ]
