# Generated by Django 5.1.6 on 2026-09-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdhapi', '0054_socialmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='github_issue',
            field=models.URLField(blank=True, help_text="GitHub's issue URL ", max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('TECHNICAL_REVIEW', 'Technical review'), ('PEER_REVIEW', 'Peer review'), ('DESIGN_REVIEW', 'Design review'), ('COPY_EDITING', 'Copy editing'), ('PUBLISHED', 'Published'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=25),
        ),
    ]
