# Generated by Django 5.1.6 on 2026-08-10 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdhapi', '0054_socialmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='abstract',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('TECHNICAL_REVIEW', 'Technical review'), ('PEER_REVIEW', 'Peer review'), ('DESIGN_REVIEW', 'Design review'), ('COPY_EDITING', 'Copy editing'), ('PUBLISHED', 'Published'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=25),
        ),
    ]
