# Generated by Django 5.1.6 on 2026-08-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdhapi', '0055_author_abstract_alter_article_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='accepted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='author',
            name='published',
            field=models.IntegerField(default=0),
        ),
    ]
