# Generated by Django 5.1.6 on 2026-09-28 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdhapi', '0055_article_github_issue_alter_article_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='github_issue',
            field=models.URLField(blank=True, help_text="GitHub's issue URL on C2DH/jdh-notebook repository", max_length=254, null=True),
        ),
    ]
