# Generated by Django 5.1.6 on 2026-08-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdhapi', '0056_author_accepted_author_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='abstract',
        ),
        migrations.AddField(
            model_name='author',
            name='abstract',
            field=models.ManyToManyField(blank=True, to='jdhapi.abstract'),
        ),
    ]
