# Generated by Django 5.1.6 on 2026-08-10 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdhapi', '0057_remove_author_abstract_author_abstract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='abstract',
        ),
        migrations.RemoveField(
            model_name='author',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='author',
            name='published',
        ),
    ]
